require_relative 'lib/katarina/version'

Gem::Specification.new do |spec|
  spec.name          = 'katarina'
  spec.version       = Katarina::VERSION
  spec.authors       = %w[masatoshi_moritsuka]
  spec.email         = %w[yakiyaki_ikayaki@yahoo.co.jp]

  spec.summary       = 'This gem generates type definitions for TypeScript from a OpenAPI Documentation generated by rspec-openapi.'
  spec.description   = 'This gem generates type definitions for TypeScript from a OpenAPI Documentation generated by rspec-openapi.'
  spec.homepage      = 'https://github.com/sanfrecce-osaka/katarina'
  spec.license       = 'MIT'
  spec.required_ruby_version = Gem::Requirement.new('>= 2.5.0')

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files = Dir.glob('lib/**/*') + Dir.glob('lib/.rbnext/**/*') + Dir.glob('bin/**/*') + %w[README.md LICENSE.txt]
  spec.bindir        = 'exe'
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = %w[lib]

  spec.add_dependency 'activesupport'
  spec.add_dependency 'railties'
  spec.add_dependency 'rspec-openapi'
  spec.add_dependency 'ruby-next'
end
